### PR TITLE
Get rid of the datalab package; it lives in its own repo now.

### PR DESCRIPTION
**Pull request by gramster**
Also clean up some detritus in /content. Moved the stray notebook to the notebook repo and we don't need publish.sh any more.

### CODE REVIEW

**Comment by nikhilk** [comment]
Do we really need to delete anything from this repo? Lets get the other one working, and then we can decide how to EoL this one at the right time.

**Comment by gramster** [comment]
The other one is working.

**Comment by ojarjur** [comment]
I can't speak to the readiness of the new repository, but the changes in this pull request look good to me.

**Comment by ojarjur** [comment]
LGTM

I've verified that (with https://github.com/googledatalab/datalab/pull/31), this works for all of the bundled sample notebooks (except the programming language correlations one, which tries to query a no-longer extant table).

**Comment by qimingj** [comment]
LGTM.

**Pull request merged**
