### PR TITLE
Bind to localhost only so docker does not expose the port.

### PR DESCRIPTION
**Pull request by qimingj**

### CODE REVIEW

**Comment by parthea** [comment]
LGTM! I have been using this configuration for a month now.

We could also refer users to the [Docker Advanced Networking](https://docs.docker.com/v1.5/articles/networking/) section as mentioned in #786 . The reference could be made available in the wiki, or even as a comment above the docker run command (in case users want to bind to a different interface, for example remote server access).

**Comment by gramster** [comment]
LGTM although this did not work for me on corp network. Did you try it Bradley?

**Comment by parthea** [comment]
Will this configuration work when datalab is installed on a GCE instance? (I haven't tried it)

**Comment by gramster** [comment]
Tested again; does not work on corp on Macs at least.

Probably not an issue on GCE as the GCE instance is firewalled anyway and you have to use an SSH tunnel. That is, we probably don't need it for GCE.

**Comment by nikhilk** [comment]
You do want it in GCE as well, in case someone inadvertently opens the port on the GCE firewall. This is a requirement from security folks.

**Comment by gramster** [comment]
This looks relevant: https://forums.docker.com/t/using-localhost-for-to-access-running-container/3148

**Comment by qimingj** [comment]
gram, thanks. Will do more investigation. Basically, on Linux we need the docker lever ip binding  (the change helps). On Mac, we need vitualbox level ip binding.

**Pull request closed without merging**
