### PR TITLE
Update Managing Cloud Datalab - Authentication.ipynb

### PR DESCRIPTION
**Pull request by aman-ebay**
Fix Cloud Dataproc branding.

### CODE REVIEW

**Comment by aman-ebay** [comment]
I'll be adding more commits as I go through the notebooks.

**Comment by gramster** [comment]
For the most part this looks good to me. Thanks Anthony! However, is it really necessary to change Cloud Datalab to Google Cloud Datalab? I thought either  was acceptable, and there are certainly still cases left where 'Cloud Datalab' is used, so I'm wondering what the criteria were for deciding whether to use the full name or the shorter name.

**Comment by aman-ebay** [comment]
Hi Graham,

The branding guidelines
<https://sites.google.com/a/google.com/cloud-devdocs/doc-authoring-and-style-guide/branding-guidelines?pli=1>
say to use the full branding "Google [product-name] on first use on a page
(quoted, below), and then only the product name (e.g., Cloud Datalab) in
later references. That's why I tried to add the "Google" prefix to "Cloud
Datalab" on the first reference on each page.


   - *Long name *should be used on the first instance in a topic.


Tony

**Comment by gramster** [comment]
Gotcha, that makes more sense then.

**Comment by gramster** [comment]
Lots of merge conflicts so I have rebased this into a new branch 'branding'.

**Pull request closed without merging**
