### PR TITLE
Updated nbconvert.py to use insert with 2 arguments.

### PR DESCRIPTION
**Pull request by supriyagarg**
Now '/datalab/nbconvert' is inserted into the first position.
This fixes the bug #820.

### CODE REVIEW

**Comment by gramster** [comment]
I think we should use insert(0,...) instead; we want to take priority over any default templates.

**Comment by supriyagarg** [comment]
Done.

**Comment by gramster** [comment]
LGTM, thanks!

**Comment by supriyagarg** [comment]
The PR #823 addresses the same bug using prepend.

**Pull request closed without merging**
